blank_issues_enabled: false
contact_links:
  - name: Advice and general questions
    url: https://stackoverflow.com/questions/tagged/ARCore
    about: For advice and general questions, please use the ARCore tag on Stack Overflow.
  - name: ARCore SDK for Android
    url: https://github.com/google-ar/arcore-android-sdk/issues
    about: If using Android Studio, please use the https://github.com/google-ar/arcore-android-sdk issue tracker instead.

  - name: Developer documentation
    url: https://developers.google.com/ar/develop/unity/
    about: Check out the developer documentation in case your question has already been answered.
  - name: API reference documentation
    url: https://developers.google.com/ar/reference/unity/
    about: For API questions, refer to the API reference documentation.
